[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_mint = "BQjcQ3DQ9zDG3kSnR8dcdst2Te1953B86DQHP2GSKt75"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/goldhorse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
