[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_spl_token = "ACoCmW8G4CbQtrre2VknFk9SFGjCkoYdkwD2FvwsJh5H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/danny/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
